steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
  
  # Build the project
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'

  # 1. Build dell'immagine Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mia-app:$COMMIT_SHA', '.']

  # 2. Push dell'immagine nel registro (PKG DOCKER)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mia-app:$COMMIT_SHA']

  # 3. Deployment (es. su Cloud Run o VM come indicato nello schema)
  - name: 'gcr.io/://google.com'
    entrypoint: gcloud
    args:
# Option to save build artifacts if needed
# artifacts:
#   objects:
#     location: 'gs://$PROJECT_ID/build'
#     paths: ['dist/**']
